clone repo version name

diff --git a/.github/workflows/deployDist.yaml b/.github/workflows/deployDist.yaml
--- a/.github/workflows/deployDist.yaml
+++ b/.github/workflows/deployDist.yaml
@@ -9,6 +9,6 @@ jobs:
                 echo "Cloneing repository..."
                 echo "${{toJson(github)}}"
                 git clone https://github.com/${{github.repository}}.git
-                - name: "Install Node.js"
-                run: node -version || echo "Node.js not found"
+            - name: "Install Node.js"
+              run: node -version || echo "Node.js not found"
                 echo "Atul Joshi Is Using Github Actions"
